name: Auto publish

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'
  

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: rebuild
      run: |
        git config --global user.name 'Gitub Action Bot'
        git config --global user.email 'wilfried.woivre@users.noreply.github.com'
        git commit --amend --no-edit
        git push --force-with-lease
