name: Generate monthly news

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate news post for the current month
        shell: pwsh
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./utils/generate-monthly-news.ps1 -monthTosubstract 0

      - name: Commit and push
        shell: bash
        run: |
          git config --global user.name 'Github Action Bot'
          git config --global user.email 'wilfried.woivre@users.noreply.github.com'
          git add _news
          git diff --quiet && git diff --staged --quiet || git commit -m "Update monthly news post"
          git pull --rebase
          git push
