name: Generate Issue

on:
  workflow_dispatch:
  push:
  

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Check jq
      run: |
        jq --version
      shell: bash

    - name: create-issue
      run: |
        for entry in `ls ./_posts`; do
          if grep -w 'githubcommentIdtoreplace: ' "./_posts/$entry"; then
              echo "$entry need to be updated"

              title=$(grep -w 'title:' "./_posts/$entry")
              echo $title
              issueTitle="$(echo "${title/"title:"/""}"  | xargs -0 echo -n)"
              echo "$issueTitle"
              response=$(curl --request POST --url https://api.github.com/repos/${{ github.repository }}/issues --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' --header 'Content-Type: application/json' --data "{\"title\": \"$issueTitle\", \"body\": \"This issue was automatically created by the GitHub Action workflow\", \"assignees\": [\"wilfriedwoivre\"] }")
              echo "$response"
              issueNumber=$(echo "$response" | jq '.number')
              echo "$issueNumber"

              if [[ "null" != "$issueNumber" ]]; then
                sed -i "s/githubcommentIdtoreplace:/comments_id: $issueNumber/g" "./_posts/$entry"

                echo "$entry has been updated"
              fi
          else
              echo "$entry has already an assigned issue"
          fi
        done

        git config --global user.name 'Github Action Bot'
        git config --global user.email 'wilfried.woivre@users.noreply.github.com'
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -am "Add comment id"
        git pull --rebase
        git push
      shell: bash

      